### ISSUE TITLE
Fails to show harpoon marks

### ISSUE THREAD

**Issue by mystilleef** [brandoncc/telescope-harpoon.nvim#1] opened 2021-11-22 12:18 UTC
Was this extension merged into `harpoon`? I can't get it working. It doesn't show marks.

**Comment by brandoncc** [comment] 2021-11-23 07:11
Thanks for opening this issue. I created this extension not long after harpoon was created, and the API had changed since then. There has been talk about merging this with the harpoon repo, but I haven't had time.

I just pushed a fix. The plugin should work as intended now. If you have any other issues, please let me know.

**Closed as completed by brandoncc** 2021-11-23 07:11 UTC
